version: "3.1"
services:
    www:
        container_name: appmax-www
        build: .
        ports:
            # - "80:80"
            - "80:80"
        volumes:
            - ./www:/var/www/html/
            - ./docker-conf/php:/usr/local/etc/php/
        links:
            - db
        networks:
           - default
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: appmax_api
            MYSQL_USER: appmax_api
            MYSQL_PASSWORD: provaAppMax2020!
            MYSQL_ROOT_PASSWORD: root
#            TZ: Brazil/West
            TZ: America/Recife
        volumes:
            # - ./dumps:/docker-entrypoint-initdb.d
            - ./docker-conf/my.cnf:/etc/mysql/my.cnf
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8800:80"
        environment:
            MYSQL_USER: appmax_api
            MYSQL_PASSWORD: provaAppMax2020!
            MYSQL_ROOT_PASSWORD: root
volumes:
  persistent:
